services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend/pizzaria.db:/app/pizzaria.db
    env_file:
      - ./backend/.env

  frontend:
    build: .
    ports:
      - "8080:80"
    depends_on:
      - backend
